#!/usr/bin/env bash
# Use this script to connect Colab notebook to a local runtime

if [ -z "$(which jupyter-notebook)" ] ; then
  echo "password is required for sudo command to install jupyter-notebook"
  sudo apt install jupyter-notebook --no-install-recommends
fi

if [ -z "$1" ]; then port="8888"; else port="$1"; fi
jupyter notebook \
  --NotebookApp.allow_origin='https://colab.research.google.com' \
  --port="$port" \
  --NotebookApp.port_retries=0 &


